import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';

import { routes } from './app.routes';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';
import { provideIcons } from '@ng-icons/core';
import { 
  bootstrapHeart,
  bootstrapStar,
  bootstrapStarFill,
  bootstrapGithub,
  bootstrapTwitter,
  bootstrapSearch,
  bootstrapHouse,
  bootstrapBook,
  bootstrapFolder,
  bootstrapFileText,
  bootstrapChevronRight,
  bootstrapChevronDown,
  bootstrapArrowLeft,
  bootstrapArrowRight,
  bootstrapX,
  bootstrapCheckCircle,
  bootstrapInfoCircle,
  bootstrapExclamationTriangle,
} from '@ng-icons/bootstrap-icons';
import {
  heroUsers,
  heroHome,
  heroCog,
  heroDocument,
  heroFolder,
  heroMagnifyingGlass,
  heroArrowLeft,
  heroArrowRight,
  heroXMark,
  heroCheckCircle,
  heroInformationCircle,
  heroExclamationTriangle,
  heroSun,
  heroMoon,
  heroBars3,
  heroLink,
} from '@ng-icons/heroicons/outline';
import {
  // UI icons
  lucideSearch,
  lucideHome,
  lucideBook,
  lucideFolder,
  lucideFile,
  lucideChevronRight,
  lucideChevronDown,
  lucideArrowLeft,
  lucideArrowRight,
  lucideX,
  lucideCheck,
  lucideInfo,
  lucideAlertTriangle,
  lucideSun,
  lucideMoon,
  lucideMenu,
  lucideLink,
  // Content icons - Common RPG/D&D icons
  lucideSword,
  lucideSwords,
  lucideShield,
  lucideShieldAlert,
  lucideShieldCheck,
  lucideWand2,
  lucideSkull,
  lucideHeart,
  lucideDices,
  lucideTarget,
  lucideBan,
  lucideZap,
  lucideSnowflake,
  lucideFlame,
  lucideDrama,
  lucideEye,
  lucideBrain,
  lucideWind,
  lucideCross,
  lucideSparkles,
  lucideScroll,
  lucideCrown,
  lucideCoins,
  lucideAlertCircle,
  lucideLock,
  lucideUnlock,
  lucideActivity,
  lucideAnchor,
  lucideArchive,
  lucideAward,
  lucideBeaker,
  lucideBell,
  lucideBookOpen,
  lucideBox,
  lucideBriefcase,
  lucideCalendar,
  lucideCircle,
  lucideCloud,
  lucideCompass,
  lucideFeather,
  lucideGift,
  lucideGlobe,
  lucideHash,
  lucideHelpCircle,
  lucideKey,
  lucideMap,
  lucideMapPin,
  lucidePackage,
  lucideSettings,
  lucideStar,
  lucideTrophy,
  lucideUser,
  lucideUsers,
  lucideZapOff,
} from '@ng-icons/lucide';
import {
  // Game Icons - Comprehensive RPG set
  gameRollingDices,
  gameSwordman,
  gameShield,
  gameBroadsword,
  gameBattleAxe,
  gameBowArrow,
  gameMagicSwirl,
  gameSpellBook,
  gameScrollUnfurled,
  gamePotionBall,
  gameHealthPotion,
  gameSkullCrossedBones,
  gameDragonHead,
  gameWingCloak,
  gameTreasureMap,
  gameChestArmor,
  gameHelmet,
  gameBootKick,
  gameDiamondRing,
  gameCrossedSwords,
  gameFireBowl,
  gameIceBolt,
  gameLightningTrio,
  gamePoisonGas,
  gameHealingShield,
  gameStoneBlock,
  gameSpikyExplosion,
  gameCrystalWand,
  gameCrownedSkull,
  gameDeathSkull,
  gameElfHelmet,
  gameEnergySword,
  gameFairyWand,
  gameGooSkull,
  gameHandSaw,
  gameLightningBow,
  gameMaceHead,
  gameMinotaur,
  gameOrcHead,
  gamePirateHat,
  gameWizardFace,
} from '@ng-icons/game-icons';

/**
 * Application configuration
 * 
 * Design decisions:
 * - HttpClient with fetch API for better performance and SSR compatibility
 * - Client hydration for improved initial page load
 * - Event replay for better user experience during hydration
 * - ng-icons for comprehensive icon library with tree-shaking
 */
export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withFetch()),
    provideClientHydration(withEventReplay()),
    provideIcons({
      // Bootstrap Icons
      bootstrapHeart,
      bootstrapStar,
      bootstrapStarFill,
      bootstrapGithub,
      bootstrapTwitter,
      bootstrapSearch,
      bootstrapHouse,
      bootstrapBook,
      bootstrapFolder,
      bootstrapFileText,
      bootstrapChevronRight,
      bootstrapChevronDown,
      bootstrapArrowLeft,
      bootstrapArrowRight,
      bootstrapX,
      bootstrapCheckCircle,
      bootstrapInfoCircle,
      bootstrapExclamationTriangle,
      // Heroicons
      heroUsers,
      heroHome,
      heroCog,
      heroDocument,
      heroFolder,
      heroMagnifyingGlass,
      heroArrowLeft,
      heroArrowRight,
      heroXMark,
      heroCheckCircle,
      heroInformationCircle,
      heroExclamationTriangle,
      heroSun,
      heroMoon,
      heroBars3,
      heroLink,
      // Lucide Icons - UI
      lucideSearch,
      lucideHome,
      lucideBook,
      lucideFolder,
      lucideFile,
      lucideChevronRight,
      lucideChevronDown,
      lucideArrowLeft,
      lucideArrowRight,
      lucideX,
      lucideCheck,
      lucideInfo,
      lucideAlertTriangle,
      lucideSun,
      lucideMoon,
      lucideMenu,
      lucideLink,
      // Lucide Icons - Content (RPG/D&D)
      lucideSword,
      lucideSwords,
      lucideShield,
      lucideShieldAlert,
      lucideShieldCheck,
      lucideWand2,
      lucideSkull,
      lucideHeart,
      lucideDices,
      lucideTarget,
      lucideBan,
      lucideZap,
      lucideSnowflake,
      lucideFlame,
      lucideDrama,
      lucideEye,
      lucideBrain,
      lucideWind,
      lucideCross,
      lucideSparkles,
      lucideScroll,
      lucideCrown,
      lucideCoins,
      lucideAlertCircle,
      lucideLock,
      lucideUnlock,
      lucideActivity,
      lucideAnchor,
      lucideArchive,
      lucideAward,
      lucideBeaker,
      lucideBell,
      lucideBookOpen,
      lucideBox,
      lucideBriefcase,
      lucideCalendar,
      lucideCircle,
      lucideCloud,
      lucideCompass,
      lucideFeather,
      lucideGift,
      lucideGlobe,
      lucideHash,
      lucideHelpCircle,
      lucideKey,
      lucideMap,
      lucideMapPin,
      lucidePackage,
      lucideSettings,
      lucideStar,
      lucideTrophy,
      lucideUser,
      lucideUsers,
      lucideZapOff,
      // Game Icons (RPG themed - 4,000+ icons)
      gameRollingDices,
      gameSwordman,
      gameShield,
      gameBroadsword,
      gameBattleAxe,
      gameBowArrow,
      gameMagicSwirl,
      gameSpellBook,
      gameScrollUnfurled,
      gamePotionBall,
      gameHealthPotion,
      gameSkullCrossedBones,
      gameDragonHead,
      gameWingCloak,
      gameTreasureMap,
      gameChestArmor,
      gameHelmet,
      gameBootKick,
      gameDiamondRing,
      gameCrossedSwords,
      gameFireBowl,
      gameIceBolt,
      gameLightningTrio,
      gamePoisonGas,
      gameHealingShield,
      gameStoneBlock,
      gameSpikyExplosion,
      gameCrystalWand,
      gameCrownedSkull,
      gameDeathSkull,
      gameElfHelmet,
      gameEnergySword,
      gameFairyWand,
      gameGooSkull,
      gameHandSaw,
      gameLightningBow,
      gameMaceHead,
      gameMinotaur,
      gameOrcHead,
      gamePirateHat,
      gameWizardFace,
    })
  ]
};
